# Generated by Django 4.1.3 on 2023-04-19 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mess', '0002_feedback_goldtoken_goldtokenprice_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='silvertoken',
            old_name='time',
            new_name='tokenTime',
        ),
        migrations.RemoveField(
            model_name='goldtoken',
            name='time',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.RemoveField(
            model_name='silvertoken',
            name='day',
        ),
        migrations.RemoveField(
            model_name='silvertoken',
            name='expiryTime',
        ),
        migrations.RemoveField(
            model_name='silvertoken',
            name='used',
        ),
        migrations.RemoveField(
            model_name='student',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='isGoldMember',
        ),
        migrations.AddField(
            model_name='silvertoken',
            name='tokenDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='goldtoken',
            name='TokenCount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
