# Generated by Django 4.1.3 on 2023-02-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_remove_menu_days_menu_day_alter_feedback_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='meal',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.AddField(
            model_name='menu',
            name='meal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
