# Generated by Django 4.1.3 on 2023-02-06 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mess', '0003_remove_menu_meal_delete_food_menu_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='FirstName',
            field=models.CharField(default='Akash', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='LastName',
            field=models.CharField(default='Singh', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
