# Generated by Django 4.1.3 on 2023-02-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_remove_student_name_student_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldTokenPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TokenCount', models.IntegerField()),
                ('Price', models.FloatField()),
            ],
        ),
    ]
