# Generated by Django 4.1.3 on 2023-04-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_remove_noteatingtoday_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteatingtoday',
            name='date',
            field=models.DateField(),
        ),
    ]
