# Generated by Django 4.1.3 on 2023-02-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_remove_student_name_student_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldtoken',
            name='time',
            field=models.CharField(choices=[('0', 'Morning'), ('1', 'AfterNoon'), ('2', 'Night')], default='0', max_length=1),
        ),
    ]
