# Generated by Django 4.1.3 on 2023-02-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0005_goldtokenprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silvertoken',
            name='expiryDate',
        ),
        migrations.AddField(
            model_name='silvertoken',
            name='expiryTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='silvertoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
